### ISSUE TITLE
Add automatical saving conversation in local storage

### ISSUE THREAD

**Issue by chewmanji** [Solvro/web-promochator#13]
- implement automatical saving conversation to local storage when user sends their prompt

**Comment by mejsiejdev** [comment]
do we just save the suggested supervisor here, or the whole conversation?

**Comment by chewmanji** [comment]
I suggested saving only supervisor, however design is made for whole conversation.
We'll need to discuss about it I guess

**Comment by chewmanji** [comment]
I think we can switch this task to *saving conversation to local storage* - saving should happen automatically after user sends prompt.
Saving specific supervisor will be in another issue.
What do you think guys? @mejsiejdev @maciejkrol18

**Comment by mejsiejdev** [comment]
I agree, that's better
