### ISSUE TITLE
Refactor suggested supervisors component in the design

### ISSUE THREAD

**Issue by chewmanji** [Solvro/web-promochator#23]
As it's mentioned on Discord we need to refactor the supervisor component design:
- use accordion to wrap list of supervisors - make them one under the other
- add star icon next to each supervisor for saving

**Comment by muclx** [comment]
https://www.figma.com/design/QDsrtQPW5V11HoutborK40/PromoCHATor?node-id=307-3&t=hBzxstDo0sNgW23Q-1
