### ISSUE TITLE
Add logic for "new chat" button

### ISSUE THREAD

**Issue by chewmanji** [Solvro/web-promochator#34]
the button:
![Image](https://github.com/user-attachments/assets/a3aaa2d7-f895-4a8c-8b97-01fbeec37619)

**Comment by mejsiejdev** [comment]
Should the button redirect to `/chat` or display a modal where you input a new prompt?

**Comment by maciejkrol18** [comment]
> Should the button redirect to `/chat` or display a modal where you input a new prompt?

New chat buttons in ChatGPT and Claude both redirect the user to the chat route ("/" in ChatGPT, "/new" in Claude)

**Comment by mejsiejdev** [comment]
so it just has to be a link, yes?

**Comment by chewmanji** [comment]
yup, that's called nano task I guess 😆
