### ISSUE TITLE
Display most recent chats at the top

### ISSUE THREAD

**Issue by maciejkrol18** [Solvro/web-promochator#60]
Currently the **oldest** chats appear at the top of the sidebar, while the **recent** ones appear at the bottom. New entries should definitely appear at the top. **Same with the supervisors**

![Image](https://github.com/user-attachments/assets/d466e7d5-c1da-448a-920e-26f81fd30cbb)

**Comment by chewmanji** [comment]
We may add timestamp when creating a chat - it would also allow to group chats by elapsed time

**Comment by maciejkrol18** [comment]
> We may add timestamp when creating a chat - it would also allow to group chats by elapsed time

This is not needed if we just want to fix the order of appearance. Current chat adding logic looks like so:
```tsx
const addChat = useCallback(
  (newChat: Chat) => {
    setChats((previousChats) => [...previousChats, newChat]);
  },
  [setChats],
);
```
First we spread the old array and then add the `newChat` to the end of it. We should do the opposite:
```tsx
const addChat = useCallback(
  (newChat: Chat) => {
    setChats((previousChats) => [newChat, ...previousChats]);
  },
  [setChats],
);
```
Same with the supervisors. Fixed logic:
```tsx
const addSupervisor = useCallback(
  (supervisor: SavedSupervisor) => {
    setSupervisors((previousSupervisors) => [
      supervisor,
      ...previousSupervisors,
    ]);
  },
  [setSupervisors],
);
```
**However**, we can add timestamps if we also want to implement something like ChatGPT's feature of dividing the chat history by date last visited

**Comment by chewmanji** [comment]
Good point - I think the timestamps are overkill for us since probability that user will have more than 5 saved chats is pretty low IMO.  So changing order of items in chats/supervisor in lists is enough for now I guess

What's your thoughts? @maciejkrol18

**Comment by maciejkrol18** [comment]
> Good point - I think the timestamps are overkill for us since probability that user will have more than 5 saved chats is pretty low IMO. So changing order of items in chats/supervisor in lists is enough for now I guess
> 
> What's your thoughts? [@maciejkrol18](https://github.com/maciejkrol18)

I think the timestamps would be a really neat feature but we can add them later on, definitely not needed for the MVP. Your current changes in #62 are enough
